//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------





const unsigned char battery_charging [] = {
0x03, 0xE0, 0x0F, 0xF8, 0x0F, 0xF8, 0x08, 0x08, 0x08, 0xC8, 0x08, 0xC8, 0x09, 0xC8, 0x09, 0xC8,
0x0B, 0xE8, 0x0B, 0xE8, 0x09, 0xC8, 0x09, 0xC8, 0x09, 0x88, 0x09, 0x88, 0x08, 0x08, 0x0F, 0xF8
};


const unsigned char battery_warning [] = {
                                      0x00, 0x00,
                                      0x03, 0xE0,
                                      0x0F, 0xF8,
                                      0x0F, 0xF8,
                                      0x08, 0x08,
                                  0x08, 0x88,
                                  0x08, 0x88,
                                  0x08, 0x88,
                                  0x08, 0x88,
                                  0x08, 0x88,
                                  0x08, 0x08,
                                  0x08, 0x88,
                                  0x08, 0x88,
                                  0x08, 0x08,
                                    0x0F, 0xF8,
                                    0x0F, 0xF8
};

const unsigned char battery_low [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};


const unsigned char battery_10p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_20p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_30p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_40p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_50p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_60p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_70p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_80p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_90p [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x08, 0x08,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};

const unsigned char battery_full [] = {
                                  0x00, 0x00,
                                  0x03, 0xE0,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                              0x0F, 0xF8,
                                  0x0F, 0xF8,
                                  0x0F, 0xF8
};
