
export const DEVICES_SCENE = 'DEVICES_SCENE';
export const SERVICES_SCENE = 'SERVICES_SCENE';
export const CHARACTERISTICS_SCENE = 'CHARACTERISTICS_SCENE';
export const CHARACTERISTIC_DETAILS_SCENE = 'CHARACTERISTIC_DETAILS_SCENE';

export const HOME_SCENE = 'HOME_SCENE';
export const PROFILE_SCENE = 'PROFILE_SCENE';
export const RUNNING_SCENE = 'RUNNING_SCENE';
export const SETTINGS_SCENE = 'SETTINGS_SCENE';

export const ADEVICE_SCENE = 'ADEVICE_SCENE';

export const TAB_SCENE = 'TAB_SCENE';
export const ROOT_SCENE = 'ROOT_SCENE';
export const ANOTHER_SCENE = 'ANOTHER_SCENE';
// export const ROOT_SCENE = 'ROOT_SCENE';
